# Generated by Django 4.1.1 on 2022-09-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='payment_type',
            field=models.CharField(choices=[("pul o'tkazma", "pul o'tkazma"), ('naqd', 'naqd')], default="pul o'tkazma", max_length=20),
        ),
    ]
