# Generated by Django 4.1.1 on 2022-10-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sponsor_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name']},
        ),
    ]
