# Generated by Django 4.1.1 on 2022-10-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_university_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['create_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['create_at']},
        ),
    ]
